model_name: OLMo-2-1B

model_config:

out_dir: models/olmo2_1b

precision: bf16-true

initial_checkpoint_dir:
resume: false
tokenizer_dir:

data:
  class_path: litgpt.data.LitDataMulti
  init_args:
    data_path: data/litgpt
    train_split_names:
      - dclm_olmo_litgpt_chunk_base
      - dclm_olmo_litgpt_chunk_add_1
      - dclm_olmo_litgpt_chunk_add_2
      - dclm_olmo_litgpt_chunk_add_3
      - dclm_olmo_litgpt_chunk_add_4
    val_split_name: dclm_olmo_litgpt_val
    num_workers: 32

train:
  save_interval: 10000
  log_interval: 20
  global_batch_size: 256
  micro_batch_size: 2
  lr_warmup_steps: 2000
  max_tokens: 100034101391
  max_steps:
  max_seq_length: 4096
  tie_embeddings: false
  max_norm: 1.0
  min_lr: 6e-5
  wsds_checkpoint_ratios: [1, 2, 5, 10, 15, 20, 25, 50, 100]
  wsds_base_tokens: 1000000000
  wsds_decay_fraction: 0.1

eval:
  interval: 2000
  max_new_tokens:
  max_iters: 50
  initial_validation: false
  final_validation: true

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 3e-4
    weight_decay: 0.1
    betas: [0.9, 0.95]

devices: 4
num_nodes: 1

logger_name: wandb
log:
  project: pretraining-runs
  group: pretraining
  run: olmo2-1b

seed: 42
