model_name: OLMo-2-30M

model_config:

out_dir: models/olmo2_30m_seed43

precision: bf16-true

initial_checkpoint_dir:
resume: false
tokenizer_dir:

data:
  class_path: litgpt.data.LitDataMulti
  init_args:
    data_path: data/litgpt
    train_split_names:
      - dclm_olmo_litgpt_chunk_base
    val_split_name: dclm_olmo_litgpt_val
    num_workers: 32

train:
  save_interval: 10000
  log_interval: 20
  global_batch_size: 256
  micro_batch_size: 4
  lr_warmup_steps: 2000
  max_tokens: 3000000000
  max_steps:
  max_seq_length: 4096
  tie_embeddings: false
  max_norm: 1.0
  min_lr: 6e-5
  lr_schedule: wsd
  lr_wsd_warmup_fraction: 0.1
  lr_wsd_warmup_steps_max: 2000
  lr_wsd_decay_fraction: 0.1

eval:
  interval: 2000
  max_new_tokens:
  max_iters: 50
  initial_validation: false
  final_validation: true

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 3e-4
    weight_decay: 0.1
    betas: [0.9, 0.95]

devices: 4
num_nodes: 1

logger_name: wandb
log:
  project: pretraining-runs
  group: pretraining
  run: olmo2-30m-seed43

seed: 43
